---
- hosts: all
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Install ansible
      apt:
        name: ansible
        state: present

    - name: Install VIM
      apt:
        name: vim
        state: present

    - name: Install docker
      apt:
        deb: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/docker-ce_17.03.2~ce-0~ubuntu-xenial_amd64.deb

    - name: Install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip?_ga=2.96690399.172905267.1507577283-2085671703.1507577283
        dest: /usr/local/bin
        remote_src: yes

    - name: Install packer
      unarchive:
        src: https://releases.hashicorp.com/packer/1.1.0/packer_1.1.0_linux_amd64.zip?_ga=2.202525458.2023744030.1507658325-560153522.1507658325
        dest: /usr/local/bin
        remote_src: yes
